### ISSUE TITLE
ET: Flipped I+/I- connections

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-csharp#120] opened 2019-12-09 15:30 UTC
@bbachmanNI identified that the I+ and I- connections seem to be flipped when the 5820 is connected to a scope. The I- connection is a higher voltage than the I+ connection.

**Comment by smooresni** [comment] 2019-12-10 20:05
This is expected behavior. The voltage of the envelope waveform is negative, thus the I- will have a greater value than I+.

I verified this with the existing RFIC examples. Note probe locations 9, 10, 11:

![image](https://user-images.githubusercontent.com/51342134/70563058-2bd77f00-1b53-11ea-8f3c-225aa8e23066.png)

![image](https://user-images.githubusercontent.com/51342134/70563085-398d0480-1b53-11ea-8dea-cd10cdf59e78.png)

![image](https://user-images.githubusercontent.com/51342134/70563106-414ca900-1b53-11ea-815c-c594ff429671.png)

I probed the wires for the waveforms written in both the RDLs and existing examples:

![image](https://user-images.githubusercontent.com/51342134/70564530-fda76e80-1b55-11ea-8325-22fe6766f4d3.png)

![image](https://user-images.githubusercontent.com/51342134/70564582-16b01f80-1b56-11ea-94dc-bb2fd2dba4cc.png)

**Comment by smooresni** [comment] 2019-12-10 20:07
Closing because not a bug.

@bbachmanNI let me know if you disagree.

**Closed** 2019-12-10 20:07 UTC
Labels: bug
